added simplyblock crds and custom resource (#814)
* added simplyblock crds and custom resource

* make some spec field required in crd

* moved simplyblock mgmt deployment into a single deployment

* added helm _helpers.tpl

* conditionalize ingress creation

* conditionalize MongoDBCommunity cr creation

* remove fluentbit daemonset

* added fluent-bit sidecar container

* fixed yaml identation

* use dnsPolicy: ClusterFirstWithHostNet for spdk ppd

* exclude fluentbit own logs

* shrink thanos deployments into single deployment

* improved opensearch and graylog route

* call function if monitoring is enabled

* updated monitoring endpoint format

* removed nodeExporter

* remove fdb customParameters

* specified new port for thanos components

* updated monitoring endpoint format

* updated monitoring endpoint format

* removed hostpath capacity

* fixed graylog input endpoint

* added cluster task cr and crd

* added cluster task cr and crd

* fixed task routing

* fixed object has no attribute 'cluster_id'

* set is_json true

* return JobSchedule

* decode the json first

* remove id from the dict before passing it

* remove id and uuid from the dict before passing it

* remove id, uuid and status from the dict before passing it

* remove id, uuid, status and deleted from the dict before passing it

* improved list task

* use model.uuid instead

* made some add snode param optional in api v2

* improved sn apiv2 response data

* improved sn apiv2 response data more

* set grafana_secret empty if monitoring is disabled

* return the mgmt ip without kubelet ping

* updated the fdb health check logic

* updated crd clusterInfo

* added cr_name, cr_namespace and cr_plural to baseModel

* removed cr_name, cr_namespace and cr_plural to baseModel

* added cluster cr status patch

* added cluster cr status patch for rebalancing

* added function for patching node cr status

* added function for patching node cr device status

* added service account across mgmt services

* added patch for pool cr

* removed mode from snode model

* added rbac for simplyblock cr resource

* get cr base on node_uuid or node_mgmt_ip

* fixed patch_cr_node_status() missing 1 required keyword-only argument: 'node_mgmt_ip'

* updated storagenode crd memory status field

* update snode cr nvmf and lvol port

* updated cr kind

* updated the crds

* updated service account resource name

* updated pool resource name

* updated crd

* updated crd

* removed capacityInfo in crd

* added lvols_cr to pool model

* added lvol crd

* updated lvol api response

* updated lvol api response

* updated lvol crd

* updated lvol crd

* added func patch_cr_lvol_status

* fixed type check failure

* fixed type check failure

* added logic for updating lvol cr field

* fixed TypeError: unsupported operand type

* fixed type check failure

* update snode cr health type to bool

* updated the lvol cr change condition

* added log message

* added log message

* updated lvol cr name

* removed debug logs

* fixed linter issue

* added node permission

* updated ap/v2 cluster create response data

* updated ap/v2 cluster create response data

* removed coding from field

* updated ap/v2 cluster create response data

* added restart on another host support in api v2

* added default value for node_address

* removed default value for node_address

* updated simplyblockstoragenode crd

* updated manager permissions

* updated simplyblockpools crd

* updated simplyblock manager image tag

* added param id_device_by_nqn to snode add

* updated simplyblockstoragenode crd

* always add new devices when restarting node on new ip

* attach fluentbit container to webapi pod

* updated simplyblockstoragenode crd

* fixed helm template structure

* bind root to container host path

* bind root to container host path

* bind root to container host path

* bind root to container host path

* updated simplyblockstoragecluster crd

* updated sbcli helm values.yaml structure

* added helm value for simplyblock CR

* support storage node remove and delete in one endpoint

* remove node details from CR

* added api for cluster expansion

* updated simplyblockstoragecluster crd

* added api for device remove and restart

* added param force

* updated simplyblockdevice crd

* updated simplyblock manager image tag

* make node_address param optional during snode restart via api

* remove the worker node from list upon node snode removal

* remove the worker node from list upon node snode removal

---------

Co-authored-by: hamdykhader <hamdy.khader@gmail.com>